blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

generator/urls.py
from django.urls import path
from . import views

app_name = 'generator'

urlpatterns = [
    path('', views.password_generator, name='password_generator'),
    path('generatedpassword', views.password, name='password'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('generator/', include('generator.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from .models import models

class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

generator/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog
def all_blogs(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html', {'blogs': blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})

generator/views.py
from django.shortcuts import render
import random

def password_generator(request):
    return render(request, 'generator/password_generator.html')

def password(request):
    thepassword = ''
    characters = list('abcdefghijklmnopqrstuvwxyz')
    
    if request.GET.get('uppercase'):
        upperChars = list()
        for x in range(len(characters)):
            upperChars.append(characters[x].upper()) 
        characters += upperChars
    if request.GET.get('special'):
        characters.extend(list('!@#$%^&*()'))
    if request.GET.get('numbers'):
        characters.extend(list('1234567890'))
    length = int(request.GET.get('length', 12))
    
    for x in range(length):
        thepassword += random.choice(characters)
    return render(request, 'generator/password.html', {'password': thepassword})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects} )

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}


<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h2 class="text-center mb-5">Erik has written {{ blogs.count }} blog{{ blogs.count|pluralize }} </h2>



{% for blog in blogs %}
<div class="row justify-content-center my-3">
    <div class="col-md-10">
      <a href="{% url 'blog:detail' blog.id %}">
        <h2>{{ blog.title }}</h2>
      </a>
      <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
      <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
    </div>
</div>
{% endfor %}

{% endblock content %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>

<h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>

<p class="text-center"> {{ blog.description|safe }}</p>

{% endblock content %}

generator/templates/generator/password.html
{% extends 'portfolio/base.html' %}

{% block content %}
<div class="container text-center">
    <h2>PASSWORD GENERATOR</h2>
    <h2 class="alert alert-success">{{ password }}</h2>
    <a href="{{ request.get_full_path }}" class="btn btn-info">Regenerate</a>
    <a href="{% url 'generator:password_generator' %}" class="btn btn-info">Back</a>
</div>
{% endblock content %}

generator/templates/generator/password_generator.html
{% extends 'portfolio/base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<div class="container text-center">
<body>
    <h2>Password Generator</h2>
    <form action="{% url 'generator:password'%}">
    <select name="length"> 
        <option value="6">6</option>
        <option value="7">7</option>
        <option value="8">8</option>
        <option value="9">9</option>
        <option value="10" selected="selected">10</option>
        <option value="11">11</option>
        <option value="12">12</option>
    </select> Length
    <br>
    <input type="checkbox" name="uppercase">Uppercase</input>
    <br>
    <input type="checkbox" name="numbers">Numbers</input>
    <br>
    <input type="checkbox" name="special">Special Characters</input>
    <br>
    <input type="submit" value="Generate Password" class="btn btn-primary"></input>
    <br>
    <br>
    {% comment %} <a href="{% url 'about' %}" class="btn btn-info">About</a> {% endcomment %}


</form>
</body>
</div>
</html>


{% endblock content %}

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static%}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Erik Castillo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  
  
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">
  
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
  
    <link rel="icon" type="image/png" href="{% static "portfolio/logo.svg" %}" class= "img-fluid w-50 p-3 d-none d-md-block">
  

  </head>
  <body>

    <nav id="topNav" class="navbar navbar-expand-md py-3 sticky-top bg-body-tertiary" >
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'portfolio/logo.svg/' %}" width='50', height='50' class='d-inline-block align-top' alt="Erik's Logo">
            <span>Erik Castillo</span>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse text-center" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link active btn-lg" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link btn-lg" href="{% static 'portfolio/Resume.pdf/' %}">Resume</a>
              </li>
              <li class="nav-item">
                <a class="nav-link btn-lg" href="{% url 'blog:all_blogs' %}">Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link btn-lg" href="http://www.linkedin.com/in/erik-castillo-az" target="_blank">LinkedIn</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
  <div>
    {% block content %}{% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"></script>
  </body>

  </html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}



{% load static%}

{% comment %} showcase begin {% endcomment %}
<section class="bg-dark text-light text-center text-sm-start">

  <div class="container">
    <div class='d-sm-flex align-items-center justify-content-between'>
      <div>
        <h1>Your next <span class="text-warning">Software Developer</span></h1>
        <p class="lead my-4">Highly driven, motivated, and multitalented professional
          with a bachelor’s degree in computer science and concentration in
          software development.
        </p>
        <button class="btn btn-primary btn-lg">
          Resume
        </button>
      </div>

      <img src="{% static 'portfolio/undraw.svg' %}" class='img-fluid w-50 p-3 d-none d-md-block' alt="Erik's Logo">

    </div>
  </div>

</section>

{% comment %} showcase end {% endcomment %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/sedona.jpg' %}" class="img-fluid rounded mx-auto d-block">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Erik Castillo <br> Software Engineer <br> UofA Grad <br> Magna Cum Laude</h1>
  </div>
</div>


{% comment %} second half {% endcomment %}


<!--boxes -->

<section class="container p-5">
  <h2 class="mt-5">Portfolio</h2>

  <div class="row text-center g-4">
      {% comment %} this is where the loop starts {% endcomment %}
      {% for project in projects %}
      <div class="col-lg-4 col-md-4">
          
          <div class="card bg-dark text-light">   {% comment %}took this out: style="width: 18rem;" {% endcomment %}
              <div class="card-body text-center">
                  <h1 class="card-title mb-3">{{ project.title }}</h1>
                  <p class="card-text">{{ project.description }}</p>
              </div>
              <a href="{{ project.url }}">
                  <img src="{{ project.image.url}}" class="card-img">
              </a>    
          </div> <!-- end card div-->                
      </div>
      {% endfor %}
  </div> <!--end of row class-->

</section> 
{% comment %} end projects section {% endcomment %}

<!-- Accordion -->

<section class="p-5">
  <div class="container">
    <h2 class="text-center mb-4">Frequently Asked Questions</h2>
    <div class="accordion accordion-flush" id="questions">
      <!--item 1-->
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#question-one">
            What are some languages and technical proficiencies learned from your university?
          </button>
        </h2>
        <div id="question-one" class="accordion-collapse collapse text-center" data-bs-parent="#questions">
          <div class="accordion-body"> Python | C | C++ | Java | JavaScript | HTML5 | CSS | PHP | Kotlin <br>
            SQL | R | C# | UML | VB.NET | Microsoft VS | VS Code | Wing | MySQL
            </div>
        </div>
      </div>
      <!--item 2-->
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#question-two">
            What languages and techical proficiencies have you picked up on your own?
          </button>
        </h2>
        <div id="question-two" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body"> During my initial job hunt, I recognized a few desired skills from employers that I was lacking.
            Git, GitHub, Django, and Linux, to name a few.
            Recognizing my deficient skills, I proactively 
            acquired these new abilities and utilized them to construct this website. Employing a 
            combination of Django, Python, Linux, Git, Github, Bootstrap, and VS Code, I achieved this feat.
            <br>
            You can view my <a href="https://github.com/eacastUA" target="_blank">GitHub here</a>.     
          </div>
        </div>
      </div>
      <!--item 3-->
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#question-three">
            What are some things you do on your down time?
          </button>
        </h2>
        <div id="question-three" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body">I am consistently engaged in improving the efficiency of algorithms by solving Leetcode problems. I also try to keep my
            sklls up to date by working on projects and continuosly reviewing previous topics.
           </div>
        </div>
      </div>
      {% comment %} <!-- item 4-->
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#question-four">
            Accordion Item #4
          </button>
        </h2>
        <div id="question-four" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body">Placeholder content for this accordion, which is intended to demonstrate the <code>.accordion-flush</code> class. This is the third item's accordion body. Nothing more exciting happening here in terms of content, but just filling up the space to make it look, at least at first glance, a bit more representative of how this would look in a real-world application.</div>
        </div>
      </div> {% endcomment %}
    </div>
  </div>
</section>


{% endblock content %}